### ISSUE TITLE
Problemes amb encoding quan les capçaleres estan corruptes

### ISSUE THREAD

**Issue by jaumemoral** [jaumemoral/mailtoticket#20]
He trobat aquest error
Traceback (most recent call last):
  File "/home4/users/lcfib/lcfib/mailtoticket/mailtoticket.py", line 33, in <module>
    if mail.cal_tractar():
  File "/home4/users/lcfib/lcfib/mailtoticket/mailticket.py", line 167, in cal_tractar
    if "DELIVERY FAILURE" in self.get_subject(): return False
  File "/home4/users/lcfib/lcfib/mailtoticket/mailticket.py", line 105, in get_subject
    self.tracta_subject()
  File "/home4/users/lcfib/lcfib/mailtoticket/mailticket.py", line 60, in tracta_subject
    resultat+=fragment[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)

Aixi que he intentat que quan hi ha una part sense encoding, netegi completament qualsevol caracter inferior a 128. De totes formes, la capçalera està corrupta també segons l'antivirus, aixi que estem tractant una excepció en tota regla.

No tanco perque no se si ho he solucionat.

**Comment by jaumemoral** [comment]
Encara passa de tant en tant

Traceback (most recent call last):
  File "/home4/users/lcfib/lcfib/mailtoticket/mailtoticket.py", line 33, in <module>
    if mail.cal_tractar():
  File "/home4/users/lcfib/lcfib/mailtoticket/mailticket.py", line 169, in cal_tractar
    if "Return Receipt" in self.get_body(): return False
  File "/home4/users/lcfib/lcfib/mailtoticket/mailticket.py", line 116, in get_body
    self.tracta_body()
  File "/home4/users/lcfib/lcfib/mailtoticket/mailticket.py", line 28, in tracta_body
    body=self.codifica(part)
  File "/home4/users/lcfib/lcfib/mailtoticket/mailticket.py", line 49, in codifica
    s=unicode(part.get_payload(decode=True))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 424: ordinal not in range(128)

No tinc clar estar-ho fent de la millor forma possible... Esta clar que son casos estranys, pero hauriem de poder tractar absolutament tots els mails sense que peti.

**Comment by alexm** [comment]
M'he trobat amb problemes similars a l'hora de recodificar text mal
codificat amb python. En aquests casos hem canviat l'entorn de l'script per
LANG=en_US.UTF-8 i ha funcionat.

Però estic d'acord que no hauria de fallar l'script, per tant crec que
seria millor capturar l'excepció i intentar resoldre el problema d'alguna
manera alternativa (per exemple, deixar aquest correu en una bústia pendent
de revisar i notificar-ho a algú).
El dia 09/06/2015 16:38, "Jaume Moral" <notifications@github.com> va
escriure:
